# Generated by Django 4.1.5 on 2023-03-12 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='John', max_length=255)),
                ('last_name', models.CharField(default='Doe', max_length=255)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('profile_description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_of_passenger', to='nish_go.account')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_address', models.CharField(max_length=255)),
                ('depart_date', models.DateField(default=django.utils.timezone.now)),
                ('depart_time', models.TimeField(default=django.utils.timezone.now)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='time stamp of trip creation')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('stops', models.BooleanField(default=0)),
                ('passengers_amount', models.IntegerField(default=0)),
                ('booked', models.ManyToManyField(through='nish_go.Booking', to='nish_go.account')),
                ('driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_of_trip', to='nish_go.account')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_associated_to_passenger', to='nish_go.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('account', 'trip')},
        ),
    ]
