# Generated by Django 4.1.5 on 2023-03-17 20:05

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
