# Generated by Django 4.1.5 on 2023-03-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0002_alter_trip_destination_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(max_length=255),
        ),
    ]
