# Generated by Django 4.1.5 on 2023-03-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0003_alter_trip_destination_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempSearch',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_term', models.CharField(max_length=255)),
                ('search_date', models.DateField()),
            ],
        ),
    ]
