# Generated by Django 4.1.5 on 2023-03-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0004_tempsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsearch',
            name='search_date',
            field=models.DateField(blank=True),
        ),
    ]
