# Generated by Django 4.1.5 on 2023-03-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0005_alter_tempsearch_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsearch',
            name='search_term',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
