# Generated by Django 4.1.5 on 2023-03-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0006_alter_tempsearch_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsearch',
            name='search_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tempsearch',
            name='search_term',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
