# Generated by Django 4.1.5 on 2023-03-19 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0008_alter_tempsearch_search_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsearch',
            name='search_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_associated_to_search', to='novago.account'),
        ),
    ]
