# Generated by Django 4.1.5 on 2023-03-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0009_tempsearch_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='starting_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
