# Generated by Django 4.1.5 on 2023-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0010_trip_starting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub',
            field=models.CharField(default='', max_length=250),
        ),
    ]
