# Generated by Django 4.1.5 on 2023-03-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0011_account_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3),
        ),
    ]
