# Generated by Django 4.1.5 on 2023-03-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0012_alter_account_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='driver1.jpg', upload_to='profile_pictures/'),
        ),
    ]
