# Generated by Django 4.1.5 on 2023-03-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0013_alter_account_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempSearch',
        ),
    ]
