# Generated by Django 4.1.5 on 2023-03-27 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0015_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.CharField(blank=True, max_length=420),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3),
        ),
        
    ]
