# Generated by Django 4.1.5 on 2023-03-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0020_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_of_driver', to='novago.account'),
        ),
    ]
