# Generated by Django 4.1.5 on 2023-03-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0021_alter_driver_account'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE novago_rating ADD COLUMN description varchar(255)"),
    ]
