# Generated by Django 4.1.5 on 2023-03-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0022_remove_rating_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
