# Generated by Django 4.1.5 on 2023-03-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0023_alter_rating_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('distance_meters', models.IntegerField(default=100000)),
                ('duration_mins', models.IntegerField(default=60)),
            ],
            options={
                'unique_together': {('start', 'end')},
            },
        ),
    ]
