# Generated by Django 4.1.5 on 2023-04-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novago', '0024_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
